### ISSUE TITLE
Leetcode #765 Python Error: list index out of range

### ISSUE THREAD

**Issue by saura8h** [kamyu104/LeetCode-Solutions#97]
Tried running the below code in python3 (changed `xrange` to `range`):

```
class Solution(object):
    def minSwapsCouples(self, row):
        """
        :type row: List[int]
        :rtype: int
        """
        N = len(row)//2
        couples = [[] for _ in range(N)]
        for seat, num in enumerate(row):
            couples[num//2].append(seat//2)
        adj = [[] for _ in range(N)]
        for couch1, couch2 in couples:
            adj[couch1].append(couch2)
            adj[couch2].append(couch1)

        result = 0
        for couch in range(N):
            if not adj[couch]: continue
            couch1, couch2 = couch, adj[couch].pop()
            while couch2 != couch:
                result += 1
                adj[couch2].remove(couch1)
                couch1, couch2 = couch2, adj[couch2].pop()
        return result  # also equals to N - (# of cycles)

def main():
    soln = Solution()
    arr = [1, 3, 5, 2, 4, 6, 7]
    min_swaps = soln.minSwapsCouples(arr)
    print(min_swaps)

if __name__ == '__main__':
    main()
```

With the below error:
```
Traceback (most recent call last):
  File "min_swap_couples.py", line 33, in <module>
    main()
  File "min_swap_couples.py", line 29, in main
    min_swaps = soln.minSwapsCouples(arr)
  File "min_swap_couples.py", line 10, in minSwapsCouples
    couples[num//2].append(seat//2)
IndexError: list index out of range
```

**Comment by kamyu104** [comment]
According to description: `len(row) is even`.
Your input is not as expected.
